FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG REACT_APP_NAME
ARG REACT_APP_MAC
ENV REACT_APP_NAME=$REACT_APP_NAME
ENV REACT_APP_MAC=$REACT_APP_MAC
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html