version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=Telmo Sampaio - PROD
    image: telmo87/docker-github-actions
    ports:
      - '8080:80'
